### PR TITLE
Removed all zero width space unicode chars in appdata

### PR DESCRIPTION
**Pull request by BharatKalluri**
Hey @babluboy !

There were a lot of [Zero width characters](http://www.fileformat.info/info/unicode/char/200b/index.htm) in the appdata file(?).

These characters were causing flatpak build errors.So I fixed them :-)

Cheers!

### CODE REVIEW

**Comment by babluboy** [comment]
Many thanks for this. Do let me know how you are building the Flatpak so that I can try and automate the same with TravisCI perhaps - that way the Flatpak stays updated.

We can also mention Flatpak as one of the options to install Bookworm on cross distro OSes.

**Comment by babluboy** [comment]
@BharatKalluri @btkostner I am thinking whether this change is the reason why we have the current issue of the houston script not being able to insert the stripe key for bookworm monetization due to which bookworm shows up as free instead of a monetized app on Appcenter...

Houston Issue: https://github.com/elementary/houston/issues/567
Houston Fix PR: https://github.com/elementary/houston/pull/572

**Comment by btkostner** [comment]
I'll deploy the update tonight and let you know when it's live

**Comment by babluboy** [comment]
@btkostner Thanks. Will wait for your update and check.

**Comment by btkostner** [comment]
@babluboy You should be good now. Sorry for the super long wait.

**Comment by babluboy** [comment]
@btkostner great to hear - guess it will take a while for the refresh, restarted the laptop but still see bookworm as free...

**Comment by btkostner** [comment]
Just removed the current 0.9.9 version and rebuilt it. Give it a bit

**Comment by babluboy** [comment]
@btkostner Checked AppStore today and Bookworm still shows up as free...

**Comment by btkostner** [comment]
I think this is the same issue I ran into with appstream-generator some months ago. It doesn't invalidate old packages when new metadata is discovered. You will probably need to create a new release. Sorry.

**Comment by babluboy** [comment]
@btkostner No probs. I'm in the midst of making some changes to use libxml. When that is done, I can make a release. Do I have to make any changes on the appdata xml for the release to fix the issue?

**Comment by btkostner** [comment]
Nope. I just pulled the latest version of houston and built the 0.9.9 version locally and ran into no problems.

**Comment by babluboy** [comment]
oh ok...thanks a lot

**Pull request merged**
