### PR TITLE
merge changes from master into dev

### PR DESCRIPTION
**Pull request by shiraeeshi**
This PR merges recent changes from master into dev: translations, position-related functionality, leaf-over-page-by-edge setting.

This PR is intended to make merging changes from dev into master easier, because merge conflicts are already resolved here.

@babluboy , after accepting this PR you can merge changes from dev into master, we can do that because we've added a setting to allow user to choose whether to divide chapters to pages or not. I don't know if it's a good idea though: if we leave dividing chapters to pages setting to true as default, it might be confusing for a user if it doesn't work and he sees a blank page instead of a book contents. Maybe we should make the setting disabled by default until the functionality is stable?

### CODE REVIEW

**Comment by babluboy** [comment]
Many thanks, I have merged.
The split chapters to page will need to work properly and will be the default option. The user can turn it off if required using the setting.

**Comment by shiraeeshi** [comment]
Should we merge dev into master?

**Comment by babluboy** [comment]
No..I will need to implement the pages function in dev before it can be merged into master. Currently people can get the default chapter split on master branch

**Comment by shiraeeshi** [comment]
> Currently people can get the default chapter split on master branch

The functionality was removed from the master branch by #331 PR.

**Comment by shiraeeshi** [comment]
That was a bad choice of words in my previous post. I meant should we merge changes from dev into master (without removing the dev branch)?
I want to merge little changes between branches so that we don't have to deal with complicated conflicts when merging later if master and dev branches accumulate a lot of changes.

**Comment by babluboy** [comment]
Yes that’s a good idea. Although my next change should be the pages splitting one.

**Pull request merged**
