### PR TITLE
Remove leftover spaces

### PR DESCRIPTION
**Pull request by onerbs**
I just realized that I leftover some spaces, sorry. Its fixed now. I will be more careful next time.

### CODE REVIEW

**Comment by babluboy** [comment]
No worries - I make lots of mistakes as well :-)

**Comment by babluboy** [comment]
The travis build is failing - initially it looks to be an internal travis build error. Did the code build fine for your PR ?

**Comment by onerbs** [comment]
Yes, the code builds just fine. The problem seems to araise while installing the npm package `@elementaryos/houston`. Maybe a rerun will fix it?

**Comment by babluboy** [comment]
This is a houston issue and I have fixed the same by downgrading the node_js version as per:
https://gitter.im/elementary/houston?at=5dcb28c6c26e8923c413150c

**Pull request merged**
