### PR TITLE
Enable translations

### PR DESCRIPTION
**Pull request by tintou**

### CODE REVIEW

**Comment by babluboy** [comment]
@tintou many thanks. Does this work in Launchpad ? I was using the set up to have the translations done on launchpad based on the languages used by translators ...is this a better way to have the translated po files a part of the build itself ?

I was thinking of getting the translations on to weblate and have set up the GitHub integration for weblate but have not got it working yet...does this change help integrate with weblate?

**Comment by bigbruno** [comment]
I'm install bookworm from ppa in Deepin Linux, but translation for pt_BR not applied, i'm check and files .mo is in correct folder.

Translations not working in all or just conclict in Deepin Linux?

**Comment by babluboy** [comment]
@bigbruno Translations should work (although I use the default english locale and haven't checked). I can see that the PPA has the pt_BR.po file which is being translated here at weblate:
https://hosted.weblate.org/translate/bookworm/bookworm/pt_BR/?type=all

**Comment by bigbruno** [comment]
I'm try in Brazilian Portuguese and Spanish, but no one work, if possible, please try in your PC, just nesse use LANG parameter in terminal, like this:

By the way, congratulations for your application, is best alternative for Linux, very more faster than Calibre or Okular.

lang=pt_BR bookworm

**Comment by babluboy** [comment]
I tried with LANG=pt_BR bookworm and it did not work, all strings were still in english. I will look into this tomorrow. Is there any other app that I can try in a similar way to set the language and check if the translations are working fine

**Comment by bigbruno** [comment]
Lot apps have pt_BR translation, like gedit, sorry i send wrong parameter, correct is LANGUAGE=, but i try again and really don't work in bookworm.

To try another app see in /usr/share/locale/pt_BR/LC_MESSAGES if translation file ir present, anda execute like this:

LANGUAGE=pt_BR gedit

**Comment by babluboy** [comment]
Thanks ...when I tried Noise it worked and the strings were properly translated ; `LANGUAGE=pt_BR noise`. I will do some digging to see why it is not working in bookworm

**Comment by babluboy** [comment]
I have raised a question for this at SE:
[https://elementaryos.stackexchange.com/questions/12927/language-translations-not-working-in-bookworm](https://elementaryos.stackexchange.com/questions/12927/language-translations-not-working-in-bookworm)

**Comment by babluboy** [comment]
@bigbruno I have just pushed an update into master which fixes the translation not working. Many thanks to @tintou for helping me in spotting the issue and suggesting the fix...
screenshot from 2017-08-05 17 07 38

**Comment by bigbruno** [comment]
Thank you, problem solved.

But another little problem, in .po files don't have all strings to translate, for example, "Always show library in on start" and "Enable two page reading".

**Comment by babluboy** [comment]
@bigbruno Thanks for the update. Those strings were recent additions and I had not synced the code between GH and Weblate. I have done that now and both strings are now in weblate and can be translated. Here is a direct link for the Portuguese (Brazil) one in case you are interested to do the translation: [https://hosted.weblate.org/projects/bookworm/bookworm/pt_BR/](https://hosted.weblate.org/projects/bookworm/bookworm/pt_BR/)

**Comment by bigbruno** [comment]
All strings for Brazilian Portuguese translated.

**Pull request merged**
