### PR TITLE
Fix position related functionality

### PR DESCRIPTION
**Pull request by shiraeeshi**
Depends on [Undo divide chapters to pages in master branch](https://github.com/babluboy/bookworm/pull/331) PR.

Functionality:
 - go to anchor when id after # symbol is present in link
 - go to current scroll position after checking word meaning
 - add Leaf-Over-Page-By-Edge setting that allows user to leaf over a page by clicking on its edge

### CODE REVIEW

**Comment by babluboy** [comment]
Thanks again for this PR. Now that I have merged both of your PRs, can you please take a look and ensure the functionality is fine

**Comment by shiraeeshi** [comment]
As far as I know, the functionality is fine, I checked it while debugging and coding before committing, and I've pulled the latest changes before making a PR, it's fine.

**Comment by shiraeeshi** [comment]
Pulled master branch and checked, it works as intended.

**Comment by babluboy** [comment]
Excellent - thanks a ton.
I will work on the dev branch and try to forward fix the issue and also bring in the related functions like bookmarks, etc.
The page reverse was also jumping to the first page of the chapter from the last page of the next chapter, so that needs to be fixed as well.
The pagination is a much wanted feature and should be supported by default.

**Comment by shiraeeshi** [comment]
> The pagination is a much wanted feature and should be supported by default.

We can add an entry to settings like "divide chapters to screen-sized pages" and make it enabled by default.
And then the `contentHandler` would check the setting and act accordingly.

I think it will be easier to add this setting from the beginning rather than introducing a lot of changes into the code and then adding a setting.

Can you add the setting before continuing with pagination? I can do it and create a PR.

**Pull request merged**
