### PR TITLE
shortcuts settings: gschema.xml, dialog.vala, shorcuts.vala

### PR DESCRIPTION
**Pull request by shiraeeshi**
shortcuts settings: add to gschema.xml, to dialog.vala, refactor shortcuts.vala.

UI is in Preferences Dialog - Shortcuts tab.

### CODE REVIEW

**Comment by shiraeeshi** [comment]
Shortcuts list UI is a little unwieldy, "add shortcut" button is too large, there are no column headers.
I plan to tweak and tune it and then add commits to this pull request.

**Comment by shiraeeshi** [comment]
fixes #294, #295

**Comment by shiraeeshi** [comment]
partially fixes #231

**Comment by babluboy** [comment]
@shiraeesi many thanks for your contribution. I will merge this when I get a bit of time from my day job. 
Just that I understand the work you have done, can you please attach a screenshot of the work here.

**Comment by shiraeeshi** [comment]
Here is a screenshot.
shortcuts-settings

**Comment by babluboy** [comment]
Thanks for this, I will merge soon and also may work a bit to further refine the UI for the short cuts

**Pull request merged**
