### PR TITLE
Remove stale, unreferenced es_MX.po

### PR DESCRIPTION
**Pull request by fitojb**
Hey, I’m from Mexico so this shouldn’t be seen as denigrating some dialect over others. I attempted to explain my reasoning to remove it in the commit message:

> This translation is low-quality and not as well maintained
> as es.po, but even if it was, it makes no sense for people
> to work on two translations to the same language. (The
> terminology is largely the same, and spelling is identical
> in both dialects — not at all like the Portugal–Brazil
> split).

This translation was never added to LINGUAS, so it isn’t even compiled in.

(If not done automatically somehow, please remove it from Weblate as well. Thanks!)

### CODE REVIEW

**Comment by babluboy** [comment]
@fitojb Many thanks for spotting this. Since there has been some work on the es_MX translations, I believe I missed out on adding that to the LINGUAS list. Will add that back in. 

Hopefully this approach is ok and gives someone the opportunity to improve the es_MX translations

**Comment by fitojb** [comment]
As I said, I wouldn’t like effort to be further duplicated, as there is no lexical difference (for this application) in both translations. It just wastes everyone’s time.

**Comment by babluboy** [comment]
> As I said, I wouldn’t like effort to be further duplicated, as there is no lexical difference (for this application) in both translations. It just wastes everyone’s time.

I see es_MX on the elementary translation list, so just to be consistent we can include it for Bookworm.
https://github.com/elementary/website/tree/master/_lang

**Comment by fitojb** [comment]
I’m just trying to avert a situation where every single contributor feels compelled to start a new, redundant localization and then abandoning the effort halfway, after realizing the huge long-term commitment they have to do. That’s happening to elementary now, and I’ve seen it countless times before, in my ten years of translating free software — people start new locales, they refuse to test and QA them, and then they abandon them.

**Comment by fitojb** [comment]
The problem  is that Weblate incorrectly labels `es` as “Spanish (Spain)”, prompting reactionary redundant translations from people. Weblate should only add the “Spain” moniker to `es_ES`, obviously.

The same problem happens with Qt and LibreOffice… sigh.

**Comment by fitojb** [comment]
> The problem is that Weblate incorrectly labels es as “Spanish (Spain)”, prompting reactionary redundant translations from people. Weblate should only add the “Spain” moniker to es_ES, obviously.

I’ve [fixed](https://github.com/WeblateOrg/weblate/commit/67bd4a5dbf00912405d139bfc03c4d431f088658#diff-076e8c0f965e02ae4ff8e5fbac5e493bR358) this problem at Weblate since.

**Pull request closed without merging**
